### ISSUE TITLE
Channels in RGB composite are sometimes not aligned

### ISSUE THREAD

**Issue by the-gobleo-tinkerer** [dbdexter-dev/meteor_decode#10]
I noticed that using the latest meteor_decode, the three channels can sometimes be misaligned in the RGB composite, presumably because their data start coming at different times in the recording. An example of this is below. The red channel (APID 66) is offset downwards by the height of one "strip" compared to the green and blue channels (APID 65 and 64).

![offset_channels](https://user-images.githubusercontent.com/41851763/117279857-02ab4300-ae5a-11eb-828e-b66933f28dbd.png)

The .s file that caused this problem is attached below in case it is helpful for debugging. This is only the starting section of a longer file but decoding the whole file gives the same offset effect too.

[offset_channels.zip](https://github.com/dbdexter-dev/meteor_decode/files/6433557/offset_channels.zip)

**Comment by dbdexter-dev** [comment]
Ouch, hadn't considered the case where a channel is behind the others by more than 1 line. Fixed in ca9cd3407
