### ISSUE TITLE
cc1: error: -mfloat-abi=hard: selected processor lacks an FPU (Raspberry Pi) & work-around

### ISSUE THREAD

**Issue by sgarriga** [dbdexter-dev/meteor_decode#11]
I was getting the following when building on a Raspberry Pi

~/meteor_decode/build $ make
[  4%] Building C object CMakeFiles/meteor_decode.dir/main.c.o
cc1: error: -mfloat-abi=hard: selected processor lacks an FPU
make[2]: *** [CMakeFiles/meteor_decode.dir/build.make:63: CMakeFiles/meteor_decode.dir/main.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:104: CMakeFiles/meteor_decode.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

I do have /lib/arm-linux-gnueabihf i.e. hard float, and I'm running Raspbian GNU/Linux 10 (buster)

Commenting out the is_arm check in CMakeLists.txt resolved the problem, but it's unclear if this is an all ARM or just RPi issue

**Comment by dbdexter-dev** [comment]
Hmmm.. weird. It's not an all ARM issue, I managed to compile it on both a Pi Zero and a Pi 3B with no issues, though I'm not running Raspbian on either.

A couple of questions:
- Does the issue disappear if you change `-march=native` to `-mcpu=native` at CMakeLists.txt:17 and re-enable the `is_arm` check?
- If not, which Raspberry Pi model are you compiling on?

**Comment by sgarriga** [comment]
Yes, that works, and it's a Pi Zero.

**Comment by dbdexter-dev** [comment]
Awesome, that does it then. Thanks for the help
