### ISSUE TITLE
Automatically name the output image after the input file

### ISSUE THREAD

**Issue by the-gobleo-tinkerer** [dbdexter-dev/meteor_decode#9]
I think it might be a good idea to by default name the output image after the input file's basename. For example `meteor_09-08-01_06-05-2021.s` would give `meteor_09-08-01_06-05-2021.bmp` automatically, unless specified otherwise with a `-o` parameter. What do you think @dbdexter-dev?

**Comment by dbdexter-dev** [comment]
I knew I was missing something from the previous codebase. Yes, I can add that for sure.

**Comment by dbdexter-dev** [comment]
Implemented in 622db7ee.
